### ISSUE TITLE
Adding amountGrossDimension

### ISSUE THREAD

**Issue by SalvatoreRomano1** [tracking-exposed/youtube.tracking.exposed#25]
I think that the "amountGrossDimension" variable implemented for poTREX would be really usefull also for ytTREX.
Implementing the precise amountGrossDimension would be the best also for work group analysis.
e.g. :
- have seen 1 video on yt --> amountGrossDimension=1
- have seen 2 video on yt --> amountGrossDimension=2
...

**Comment by vecna** [comment]
This is unlikely possible, because the poTREX _amountGrossDimension_ depends on something very specific of PH. on YT, we can, at our best, have a _true or false_ value if the youtube profile was logged or not.

**Comment by vecna** [comment]
in https://youtube.tracking.exposed/posts/ you'll find a link to the last post.
we can't know the amount of video watched before the extension is installed, but we detect if the profile is logged or not.

https://youtube.tracking.exposed/posts/ you'll see our last post. 

This issue is closed but #28 should consider this new field too
