### ISSUE TITLE
Incorrect watchedId records in database

### ISSUE THREAD

**Issue by cramdoulfa** [tracking-exposed/youtube.tracking.exposed#51]
I downloaded the [CSV stats](https://youtube.tracking.exposed/api/v1/videoCSV/LPRAZr2MIuE) for [this Dead Internet video](https://youtube.tracking.exposed/compare/#LPRAZr2MIuE) and I noticed that there are 20 records (the first) that have an inconsistent watchedId and watchedTitle

There seems to a set of recommendations from [this Slackline video](https://www.youtube.com/watch?v=b3vNFVfEx8E) which has been labeled with the watchedId = LPRAZr2MIuE, that of the Dead Internet video

[video-LPRAZr2MIuE-21-09-15.csv](https://github.com/tracking-exposed/youtube.tracking.exposed/files/7173421/video-LPRAZr2MIuE-21-09-15.csv)

**Comment by vecna** [comment]
this happens for a race condition, that causes the extension saves the recommendation of the previous video with the URL of the next clicked on.

- [ ] It might be fixed retroactively (by checking the presence of the the same videoId into the HTML)
- [ ] it should be fixed by properly organize the watcher/timeout

**Comment by vecna** [comment]
fixed with new version of extension. youchoose use it, guardoni use it, the online version still need to be updated.

no retroactive fixing
